---

- name: Debian-based distro detected
  block:

    - name: Removing preinstalled docker componenets.
      apt:
        purge: yes 
        state: absent
        name: "{{ CORE_TOOLS_APT_REMOVE }}"
      notify: Cleanup APT

    - name: Installing APT packages.
      apt:
        purge: yes 
        state: latest
        name: "{{ CORE_TOOLS_APT_INSTALL }}"
      notify: Cleanup APT

    - name: Installing snaps with --classic flag.
      snap:
        state: present
        classic: yes
        name: "{{ CORE_TOOLS_CLASSIC_SNAP_INSTALL }}"

    - name: Installing snaps.
      snap:
        state: present
        name: "{{ CORE_TOOLS_SNAP_INSTALL }}"

    - name: Installing dbeaver.
      snap:
        state: present
        channel: latest/edge
        name: dbeaver-ce
    
    - name: Adding user to docker group.
      shell: sudo usermod -aG docker "{{ USER }}"
      args:
        warn: no
      changed_when: false

    - name: Installing VScode extensions.
      shell:  sudo -H -u "{{ USER }}" bash -c "code --install-extension {{ item }}"
      args:
        warn: no
      with_items: "{{ VSCODE_INSTALL_EXTENSIONS }}"
      changed_when: false

  when:
    - ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"